# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalhistory',
            new_name='approvals_a_request_98049a_idx',
            old_name='approvals_a_request_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalhistory',
            new_name='approvals_a_request_09d0d3_idx',
            old_name='approvals_a_request_2_idx',
        ),
        migrations.RenameIndex(
            model_name='approvalhistory',
            new_name='approvals_a_approve_11b098_idx',
            old_name='approvals_a_approve_idx',
        ),
    ]
