# Generated by Django 5.2.8 on 2025-11-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0003_add_role_to_approvalhistory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='approvalhistory',
            name='approvals_a_role_id_idx',
        ),
    ]
