# Generated by Django 5.2.8 on 2025-11-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0005_add_template_step'),
        ('classifications', '0004_add_prs_lookups'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='approvalhistory',
            new_name='approvals_a_request_2aa2ab_idx',
            old_name='approvals_a_req_tmpl_step_idx',
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role under which the approver acted (COMPANY_ROLE lookup).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_history_roles', to='classifications.lookup'),
        ),
    ]
