name: CI

on:
  push:
  pull_request:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black flake8 mypy bandit safety
      
      - name: Code formatting check (Black)
        run: black --check --diff .
      
      - name: Lint (flake8)
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=migrations
      
      - name: Security scan (bandit)
        run: bandit -r . -x migrations,venv,env --severity-level medium
      
      - name: Dependency security check (safety)
        run: safety check --json || safety check
      
      - name: Django checks
        env:
          SECRET_KEY: dummy-secret-key-for-ci
          DEBUG: "True"
          DATABASE_URL: sqlite:///:memory:
        run: |
          python manage.py check --deploy
      
      - name: Run migrations
        env:
          SECRET_KEY: dummy-secret-key-for-ci
          DEBUG: "True"
          DATABASE_URL: sqlite:///:memory:
        run: |
          python manage.py migrate --noinput
      
      - name: Collect static files (dry run)
        env:
          SECRET_KEY: dummy-secret-key-for-ci
          DEBUG: "True"
          DATABASE_URL: sqlite:///:memory:
        run: |
          python manage.py collectstatic --noinput --dry-run

  frontend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Type check
        run: npm run typecheck
      
      - name: Lint
        run: npm run lint || echo "Linter not configured"
        continue-on-error: true
      
      - name: Build frontend
        run: npm run build
      
      - name: Verify build output
        run: |
          if [ ! -d "dist/spa" ]; then
            echo "Build output directory not found"
            exit 1
          fi
          echo "Build successful"





