# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflow',
            new_name='workflows_w_team_id_34a077_idx',
            old_name='workflows_w_team_id_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowstep',
            new_name='workflows_w_workflo_8d40e1_idx',
            old_name='workflows_w_workflo_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowstepapprover',
            new_name='workflows_w_step_id_80c8ba_idx',
            old_name='workflows_w_step_id_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowstepapprover',
            new_name='workflows_w_approve_6090ad_idx',
            old_name='workflows_w_approve_idx',
        ),
    ]
