# Generated by Django 5.2.8 on 2025-11-26 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0004_add_prs_lookups'),
        ('workflows', '0003_step_roles_use_lookup_roles'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='workflowstepapprover',
            name='workflows_w_approve_6090ad_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowstepapprover',
            new_name='workflows_w_role_id_12dde3_idx',
            old_name='workflows_w_role_id_idx',
        ),
        migrations.RemoveField(
            model_name='workflowstepapprover',
            name='approver',
        ),
        migrations.AlterField(
            model_name='workflowstepapprover',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role required to approve at this step (PRS_ROLE lookup).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_step_roles', to='classifications.lookup'),
        ),
    ]
