# Generated by Django 5.2.8 on 2025-11-26 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0004_add_prs_lookups'),
        ('workflows', '0006_migrate_workflow_to_template'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowtemplate',
            new_name='workflows_w_team_id_04f710_idx',
            old_name='workflows_w_team_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtemplate',
            new_name='workflows_w_team_id_74238a_idx',
            old_name='workflows_w_team_ver_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtemplatestep',
            new_name='workflows_w_workflo_9400b4_idx',
            old_name='workflows_wts_template_order_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtemplatestepapprover',
            new_name='workflows_w_step_id_807c57_idx',
            old_name='workflows_wtsa_step_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtemplatestepapprover',
            new_name='workflows_w_role_id_bde1c8_idx',
            old_name='workflows_wtsa_role_active_idx',
        ),
        migrations.AlterField(
            model_name='workflowstepapprover',
            name='role',
            field=models.ForeignKey(blank=True, help_text='Role required to approve at this step (COMPANY_ROLE lookup).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_step_roles', to='classifications.lookup'),
        ),
    ]
