# Generated by Django 5.2.8 on 2025-11-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0008_remove_team_from_workflow_template'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='workflowtemplate',
            new_name='workflows_w_name_3ad725_idx',
            old_name='workflows_w_name_active_idx',
        ),
        migrations.RenameIndex(
            model_name='workflowtemplate',
            new_name='workflows_w_name_ce3ea2_idx',
            old_name='workflows_w_name_ver_idx',
        ),
    ]
