# Generated by Django 5.2.8 on 2025-11-26 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prs_team_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teampurchaseconfig',
            new_name='prs_team_co_team_id_2f8c61_idx',
            old_name='prs_team_co_team_purchase_idx',
        ),
        migrations.RenameIndex(
            model_name='teampurchaseconfig',
            new_name='prs_team_co_team_id_0dd9d2_idx',
            old_name='prs_team_co_team_active_idx',
        ),
    ]
