# Generated by Django 5.2.8 on 2025-11-16 19:28

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifications', '__first__'),
        ('org', '__first__'),
        ('periods', '__first__'),
        ('reports', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rejection_comment', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='org.orgnode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='periods.financialperiod')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='reports.reportbox')),
                ('reporting_period', models.ForeignKey(limit_choices_to={'type__code': 'REPORTING_PERIOD'}, on_delete=django.db.models.deletion.PROTECT, related_name='reporting_period_submissions', to='classifications.lookup')),
                ('status', models.ForeignKey(limit_choices_to={'type__code': 'REPORT_STATUS'}, on_delete=django.db.models.deletion.PROTECT, related_name='status_submissions', to='classifications.lookup')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFieldValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('value_number', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to='report_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'xlsx', 'xls', 'csv', 'txt', 'jpg', 'png'])])),
                ('entity_ref_uuid', models.UUIDField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='reports.reportfield')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='submissions.submission')),
            ],
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['status', 'financial_period'], name='submissions_status__9a432c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('report', 'company', 'financial_period', 'reporting_period')},
        ),
        migrations.AddConstraint(
            model_name='submissionfieldvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_number__isnull', True), ('value_text__isnull', True), _connector='OR'), models.Q(('value_number__isnull', True), ('value_bool__isnull', True), _connector='OR'), models.Q(('value_number__isnull', True), ('value_date__isnull', True), _connector='OR'), models.Q(('value_number__isnull', True), ('value_file__isnull', True), _connector='OR'), models.Q(('value_number__isnull', True), ('entity_ref_uuid__isnull', True), _connector='OR'), models.Q(('value_text__isnull', True), ('value_bool__isnull', True), _connector='OR'), models.Q(('value_text__isnull', True), ('value_date__isnull', True), _connector='OR'), models.Q(('value_text__isnull', True), ('value_file__isnull', True), _connector='OR'), models.Q(('value_text__isnull', True), ('entity_ref_uuid__isnull', True), _connector='OR'), models.Q(('value_bool__isnull', True), ('value_date__isnull', True), _connector='OR'), models.Q(('value_bool__isnull', True), ('value_file__isnull', True), _connector='OR'), models.Q(('value_bool__isnull', True), ('entity_ref_uuid__isnull', True), _connector='OR'), models.Q(('value_date__isnull', True), ('value_file__isnull', True), _connector='OR'), models.Q(('value_date__isnull', True), ('entity_ref_uuid__isnull', True), _connector='OR'), models.Q(('value_file__isnull', True), ('entity_ref_uuid__isnull', True), _connector='OR')), name='single_value_column'),
        ),
        migrations.AlterUniqueTogether(
            name='submissionfieldvalue',
            unique_together={('submission', 'field')},
        ),
    ]
