# Generated by Django 5.2.8 on 2025-11-18 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifications', '0002_seed_initial'),
        ('org', '__first__'),
        ('periods', '__first__'),
        ('submissions', '0002_update_single_value_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubmissionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_submission_groups', to='org.orgnode')),
                ('financial_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_submission_groups', to='periods.financialperiod')),
                ('reporting_period', models.ForeignKey(limit_choices_to={'type__code': 'REPORTING_PERIOD'}, on_delete=django.db.models.deletion.PROTECT, related_name='report_submission_groups_by_period', to='classifications.lookup')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'REPORT_STATUS'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_submission_groups_by_status', to='classifications.lookup')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_report_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.reportsubmissiongroup'),
        ),
        migrations.AddIndex(
            model_name='reportsubmissiongroup',
            index=models.Index(fields=['status', 'financial_period'], name='submissions_status__6866ad_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportsubmissiongroup',
            unique_together={('company', 'financial_period', 'reporting_period')},
        ),
    ]
