# Generated by Django 5.2.8 on 2025-11-19 11:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifications', '0003_add_draft_status'),
        ('reports', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('node_type', models.CharField(choices=[('HOLDING', 'Holding'), ('COMPANY', 'Company')], max_length=16)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('registration_number', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('economic_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('incorporation_date', models.DateField(blank=True, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('industry', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'INDUSTRY_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='industry_nodes', to='classifications.lookup')),
                ('legal_entity_type', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'LEGAL_ENTITY_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_nodes', to='classifications.lookup')),
                ('org_type', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'ORG_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='org_type_nodes', to='classifications.lookup')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='org.orgnode')),
                ('report_groups', models.ManyToManyField(blank=True, related_name='companies', to='reports.reportgroup')),
                ('sub_industry', models.ForeignKey(blank=True, limit_choices_to={'type__code': 'SUB_INDUSTRY_TYPE'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_industry_nodes', to='classifications.lookup')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_members', to='classifications.lookup')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_classifications', to='org.orgnode')),
            ],
        ),
        migrations.AddIndex(
            model_name='orgnode',
            index=models.Index(fields=['node_type', 'is_active'], name='org_orgnode_node_ty_4acf51_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyclassification',
            unique_together={('company', 'classification')},
        ),
    ]
