# Generated by Django 5.2.8 on 2025-01-XX XX:XX

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('classifications', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('position_title', models.CharField(blank=True, max_length=128, null=True)),
                ('org_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_access_scopes', to='org.orgnode')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_scopes', to='classifications.lookup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_scopes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'org_node', 'role')},
            },
        ),
    ]

