# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_team_to_accessscope'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_user_username_unique',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='accounts_us_mobile__idx',
        ),
    ]
