# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_add_prs_support'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_request_3cca26_idx',
            old_name='audit_audit_request_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_submiss_e1c200_idx',
            old_name='audit_audit_submiss_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldchange',
            new_name='audit_field_audit_e_a2a0b1_idx',
            old_name='audit_field_audit_e_idx',
        ),
        migrations.RenameIndex(
            model_name='fieldchange',
            new_name='audit_field_audit_e_ba80f3_idx',
            old_name='audit_field_audit_e_2_idx',
        ),
    ]
