# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prs_forms', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formfield',
            new_name='prs_forms_f_templat_7eb318_idx',
            old_name='prs_forms_formfie_templat_idx',
        ),
        migrations.RenameIndex(
            model_name='formfield',
            new_name='prs_forms_f_templat_271799_idx',
            old_name='prs_forms_formfie_templat_2_idx',
        ),
        migrations.RenameIndex(
            model_name='formtemplate',
            new_name='prs_forms_f_team_id_3eb2c2_idx',
            old_name='prs_forms_formtem_team_id_idx',
        ),
        migrations.RenameIndex(
            model_name='formtemplate',
            new_name='prs_forms_f_team_id_9657e4_idx',
            old_name='prs_forms_formtem_team_id_2_idx',
        ),
    ]
