# Generated by Django 5.2.8 on 2025-11-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prs_forms', '0004_remove_team_from_form_template'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='formtemplate',
            new_name='prs_forms_f_name_c60b40_idx',
            old_name='prs_forms_formtem_name_ver_idx',
        ),
        migrations.RenameIndex(
            model_name='formtemplate',
            new_name='prs_forms_f_name_926502_idx',
            old_name='prs_forms_formtem_name_active_idx',
        ),
    ]
