/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as LoginRouteImport } from './login'
import { Route as IndexRouteImport } from './index'
import { Route as dashboardDashboardLayoutRouteImport } from './(dashboard)/_dashboardLayout'
import { Route as dashboardDashboardLayoutReportsIndexRouteImport } from './(dashboard)/_dashboardLayout/reports/index'
import { Route as dashboardDashboardLayoutReportTitlesIndexRouteImport } from './(dashboard)/_dashboardLayout/report-titles/index'
import { Route as dashboardDashboardLayoutOperationsIndexRouteImport } from './(dashboard)/_dashboardLayout/operations/index'
import { Route as dashboardDashboardLayoutInputDemoIndexRouteImport } from './(dashboard)/_dashboardLayout/input-demo/index'
import { Route as dashboardDashboardLayoutGroupsIndexRouteImport } from './(dashboard)/_dashboardLayout/groups/index'
import { Route as dashboardDashboardLayoutCompanyBasicInfoIndexRouteImport } from './(dashboard)/_dashboardLayout/company-basic-info/index'
import { Route as dashboardDashboardLayoutChangePasswordIndexRouteImport } from './(dashboard)/_dashboardLayout/change-password/index'
import { Route as dashboardDashboardLayoutBasicInfoIndexRouteImport } from './(dashboard)/_dashboardLayout/basic-info/index'
import { Route as dashboardDashboardLayoutAdminReviewIndexRouteImport } from './(dashboard)/_dashboardLayout/admin-review/index'
import { Route as dashboardDashboardLayoutAdminReviewGroupIdRouteImport } from './(dashboard)/_dashboardLayout/admin-review/$groupId'
import { Route as dashboardDashboardLayoutReportsSubmitIndexRouteImport } from './(dashboard)/_dashboardLayout/reports/submit/index'
import { Route as dashboardDashboardLayoutPrsMyRequestsIndexRouteImport } from './(dashboard)/_dashboardLayout/prs/my-requests/index'
import { Route as dashboardDashboardLayoutPrsInboxIndexRouteImport } from './(dashboard)/_dashboardLayout/prs/inbox/index'
import { Route as dashboardDashboardLayoutPrsFinanceIndexRouteImport } from './(dashboard)/_dashboardLayout/prs/finance/index'
import { Route as dashboardDashboardLayoutReportsViewGroupIdRouteImport } from './(dashboard)/_dashboardLayout/reports/view/$groupId'
import { Route as dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRouteImport } from './(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/index'
import { Route as dashboardDashboardLayoutPrsRequestsNewIndexRouteImport } from './(dashboard)/_dashboardLayout/prs/requests/new/index'
import { Route as dashboardDashboardLayoutPrsRequestsRequestIdIndexRouteImport } from './(dashboard)/_dashboardLayout/prs/requests/$requestId/index'
import { Route as dashboardDashboardLayoutPrsAdminWorkflowsIndexRouteImport } from './(dashboard)/_dashboardLayout/prs/admin/workflows/index'
import { Route as dashboardDashboardLayoutPrsAdminTeamsIndexRouteImport } from './(dashboard)/_dashboardLayout/prs/admin/teams/index'
import { Route as dashboardDashboardLayoutPrsAdminTeamConfigsIndexRouteImport } from './(dashboard)/_dashboardLayout/prs/admin/team-configs/index'
import { Route as dashboardDashboardLayoutPrsAdminFormTemplatesIndexRouteImport } from './(dashboard)/_dashboardLayout/prs/admin/form-templates/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardLayoutRoute =
  dashboardDashboardLayoutRouteImport.update({
    id: '/(dashboard)/_dashboardLayout',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardLayoutReportsIndexRoute =
  dashboardDashboardLayoutReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutReportTitlesIndexRoute =
  dashboardDashboardLayoutReportTitlesIndexRouteImport.update({
    id: '/report-titles/',
    path: '/report-titles/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutOperationsIndexRoute =
  dashboardDashboardLayoutOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutInputDemoIndexRoute =
  dashboardDashboardLayoutInputDemoIndexRouteImport.update({
    id: '/input-demo/',
    path: '/input-demo/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutGroupsIndexRoute =
  dashboardDashboardLayoutGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutCompanyBasicInfoIndexRoute =
  dashboardDashboardLayoutCompanyBasicInfoIndexRouteImport.update({
    id: '/company-basic-info/',
    path: '/company-basic-info/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutChangePasswordIndexRoute =
  dashboardDashboardLayoutChangePasswordIndexRouteImport.update({
    id: '/change-password/',
    path: '/change-password/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutBasicInfoIndexRoute =
  dashboardDashboardLayoutBasicInfoIndexRouteImport.update({
    id: '/basic-info/',
    path: '/basic-info/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutAdminReviewIndexRoute =
  dashboardDashboardLayoutAdminReviewIndexRouteImport.update({
    id: '/admin-review/',
    path: '/admin-review/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutAdminReviewGroupIdRoute =
  dashboardDashboardLayoutAdminReviewGroupIdRouteImport.update({
    id: '/admin-review/$groupId',
    path: '/admin-review/$groupId',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutReportsSubmitIndexRoute =
  dashboardDashboardLayoutReportsSubmitIndexRouteImport.update({
    id: '/reports/submit/',
    path: '/reports/submit/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutPrsMyRequestsIndexRoute =
  dashboardDashboardLayoutPrsMyRequestsIndexRouteImport.update({
    id: '/prs/my-requests/',
    path: '/prs/my-requests/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutPrsInboxIndexRoute =
  dashboardDashboardLayoutPrsInboxIndexRouteImport.update({
    id: '/prs/inbox/',
    path: '/prs/inbox/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutPrsFinanceIndexRoute =
  dashboardDashboardLayoutPrsFinanceIndexRouteImport.update({
    id: '/prs/finance/',
    path: '/prs/finance/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutReportsViewGroupIdRoute =
  dashboardDashboardLayoutReportsViewGroupIdRouteImport.update({
    id: '/reports/view/$groupId',
    path: '/reports/view/$groupId',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute =
  dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRouteImport.update(
    {
      id: '/report-titles/$reportTitleId/define-field/',
      path: '/report-titles/$reportTitleId/define-field/',
      getParentRoute: () => dashboardDashboardLayoutRoute,
    } as any,
  )
const dashboardDashboardLayoutPrsRequestsNewIndexRoute =
  dashboardDashboardLayoutPrsRequestsNewIndexRouteImport.update({
    id: '/prs/requests/new/',
    path: '/prs/requests/new/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutPrsRequestsRequestIdIndexRoute =
  dashboardDashboardLayoutPrsRequestsRequestIdIndexRouteImport.update({
    id: '/prs/requests/$requestId/',
    path: '/prs/requests/$requestId/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutPrsAdminWorkflowsIndexRoute =
  dashboardDashboardLayoutPrsAdminWorkflowsIndexRouteImport.update({
    id: '/prs/admin/workflows/',
    path: '/prs/admin/workflows/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutPrsAdminTeamsIndexRoute =
  dashboardDashboardLayoutPrsAdminTeamsIndexRouteImport.update({
    id: '/prs/admin/teams/',
    path: '/prs/admin/teams/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutPrsAdminTeamConfigsIndexRoute =
  dashboardDashboardLayoutPrsAdminTeamConfigsIndexRouteImport.update({
    id: '/prs/admin/team-configs/',
    path: '/prs/admin/team-configs/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutPrsAdminFormTemplatesIndexRoute =
  dashboardDashboardLayoutPrsAdminFormTemplatesIndexRouteImport.update({
    id: '/prs/admin/form-templates/',
    path: '/prs/admin/form-templates/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-review/$groupId': typeof dashboardDashboardLayoutAdminReviewGroupIdRoute
  '/admin-review': typeof dashboardDashboardLayoutAdminReviewIndexRoute
  '/basic-info': typeof dashboardDashboardLayoutBasicInfoIndexRoute
  '/change-password': typeof dashboardDashboardLayoutChangePasswordIndexRoute
  '/company-basic-info': typeof dashboardDashboardLayoutCompanyBasicInfoIndexRoute
  '/groups': typeof dashboardDashboardLayoutGroupsIndexRoute
  '/input-demo': typeof dashboardDashboardLayoutInputDemoIndexRoute
  '/operations': typeof dashboardDashboardLayoutOperationsIndexRoute
  '/report-titles': typeof dashboardDashboardLayoutReportTitlesIndexRoute
  '/reports': typeof dashboardDashboardLayoutReportsIndexRoute
  '/reports/view/$groupId': typeof dashboardDashboardLayoutReportsViewGroupIdRoute
  '/prs/finance': typeof dashboardDashboardLayoutPrsFinanceIndexRoute
  '/prs/inbox': typeof dashboardDashboardLayoutPrsInboxIndexRoute
  '/prs/my-requests': typeof dashboardDashboardLayoutPrsMyRequestsIndexRoute
  '/reports/submit': typeof dashboardDashboardLayoutReportsSubmitIndexRoute
  '/prs/admin/form-templates': typeof dashboardDashboardLayoutPrsAdminFormTemplatesIndexRoute
  '/prs/admin/team-configs': typeof dashboardDashboardLayoutPrsAdminTeamConfigsIndexRoute
  '/prs/admin/teams': typeof dashboardDashboardLayoutPrsAdminTeamsIndexRoute
  '/prs/admin/workflows': typeof dashboardDashboardLayoutPrsAdminWorkflowsIndexRoute
  '/prs/requests/$requestId': typeof dashboardDashboardLayoutPrsRequestsRequestIdIndexRoute
  '/prs/requests/new': typeof dashboardDashboardLayoutPrsRequestsNewIndexRoute
  '/report-titles/$reportTitleId/define-field': typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-review/$groupId': typeof dashboardDashboardLayoutAdminReviewGroupIdRoute
  '/admin-review': typeof dashboardDashboardLayoutAdminReviewIndexRoute
  '/basic-info': typeof dashboardDashboardLayoutBasicInfoIndexRoute
  '/change-password': typeof dashboardDashboardLayoutChangePasswordIndexRoute
  '/company-basic-info': typeof dashboardDashboardLayoutCompanyBasicInfoIndexRoute
  '/groups': typeof dashboardDashboardLayoutGroupsIndexRoute
  '/input-demo': typeof dashboardDashboardLayoutInputDemoIndexRoute
  '/operations': typeof dashboardDashboardLayoutOperationsIndexRoute
  '/report-titles': typeof dashboardDashboardLayoutReportTitlesIndexRoute
  '/reports': typeof dashboardDashboardLayoutReportsIndexRoute
  '/reports/view/$groupId': typeof dashboardDashboardLayoutReportsViewGroupIdRoute
  '/prs/finance': typeof dashboardDashboardLayoutPrsFinanceIndexRoute
  '/prs/inbox': typeof dashboardDashboardLayoutPrsInboxIndexRoute
  '/prs/my-requests': typeof dashboardDashboardLayoutPrsMyRequestsIndexRoute
  '/reports/submit': typeof dashboardDashboardLayoutReportsSubmitIndexRoute
  '/prs/admin/form-templates': typeof dashboardDashboardLayoutPrsAdminFormTemplatesIndexRoute
  '/prs/admin/team-configs': typeof dashboardDashboardLayoutPrsAdminTeamConfigsIndexRoute
  '/prs/admin/teams': typeof dashboardDashboardLayoutPrsAdminTeamsIndexRoute
  '/prs/admin/workflows': typeof dashboardDashboardLayoutPrsAdminWorkflowsIndexRoute
  '/prs/requests/$requestId': typeof dashboardDashboardLayoutPrsRequestsRequestIdIndexRoute
  '/prs/requests/new': typeof dashboardDashboardLayoutPrsRequestsNewIndexRoute
  '/report-titles/$reportTitleId/define-field': typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(dashboard)/_dashboardLayout': typeof dashboardDashboardLayoutRouteWithChildren
  '/(dashboard)/_dashboardLayout/admin-review/$groupId': typeof dashboardDashboardLayoutAdminReviewGroupIdRoute
  '/(dashboard)/_dashboardLayout/admin-review/': typeof dashboardDashboardLayoutAdminReviewIndexRoute
  '/(dashboard)/_dashboardLayout/basic-info/': typeof dashboardDashboardLayoutBasicInfoIndexRoute
  '/(dashboard)/_dashboardLayout/change-password/': typeof dashboardDashboardLayoutChangePasswordIndexRoute
  '/(dashboard)/_dashboardLayout/company-basic-info/': typeof dashboardDashboardLayoutCompanyBasicInfoIndexRoute
  '/(dashboard)/_dashboardLayout/groups/': typeof dashboardDashboardLayoutGroupsIndexRoute
  '/(dashboard)/_dashboardLayout/input-demo/': typeof dashboardDashboardLayoutInputDemoIndexRoute
  '/(dashboard)/_dashboardLayout/operations/': typeof dashboardDashboardLayoutOperationsIndexRoute
  '/(dashboard)/_dashboardLayout/report-titles/': typeof dashboardDashboardLayoutReportTitlesIndexRoute
  '/(dashboard)/_dashboardLayout/reports/': typeof dashboardDashboardLayoutReportsIndexRoute
  '/(dashboard)/_dashboardLayout/reports/view/$groupId': typeof dashboardDashboardLayoutReportsViewGroupIdRoute
  '/(dashboard)/_dashboardLayout/prs/finance/': typeof dashboardDashboardLayoutPrsFinanceIndexRoute
  '/(dashboard)/_dashboardLayout/prs/inbox/': typeof dashboardDashboardLayoutPrsInboxIndexRoute
  '/(dashboard)/_dashboardLayout/prs/my-requests/': typeof dashboardDashboardLayoutPrsMyRequestsIndexRoute
  '/(dashboard)/_dashboardLayout/reports/submit/': typeof dashboardDashboardLayoutReportsSubmitIndexRoute
  '/(dashboard)/_dashboardLayout/prs/admin/form-templates/': typeof dashboardDashboardLayoutPrsAdminFormTemplatesIndexRoute
  '/(dashboard)/_dashboardLayout/prs/admin/team-configs/': typeof dashboardDashboardLayoutPrsAdminTeamConfigsIndexRoute
  '/(dashboard)/_dashboardLayout/prs/admin/teams/': typeof dashboardDashboardLayoutPrsAdminTeamsIndexRoute
  '/(dashboard)/_dashboardLayout/prs/admin/workflows/': typeof dashboardDashboardLayoutPrsAdminWorkflowsIndexRoute
  '/(dashboard)/_dashboardLayout/prs/requests/$requestId/': typeof dashboardDashboardLayoutPrsRequestsRequestIdIndexRoute
  '/(dashboard)/_dashboardLayout/prs/requests/new/': typeof dashboardDashboardLayoutPrsRequestsNewIndexRoute
  '/(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/': typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-review/$groupId'
    | '/admin-review'
    | '/basic-info'
    | '/change-password'
    | '/company-basic-info'
    | '/groups'
    | '/input-demo'
    | '/operations'
    | '/report-titles'
    | '/reports'
    | '/reports/view/$groupId'
    | '/prs/finance'
    | '/prs/inbox'
    | '/prs/my-requests'
    | '/reports/submit'
    | '/prs/admin/form-templates'
    | '/prs/admin/team-configs'
    | '/prs/admin/teams'
    | '/prs/admin/workflows'
    | '/prs/requests/$requestId'
    | '/prs/requests/new'
    | '/report-titles/$reportTitleId/define-field'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin-review/$groupId'
    | '/admin-review'
    | '/basic-info'
    | '/change-password'
    | '/company-basic-info'
    | '/groups'
    | '/input-demo'
    | '/operations'
    | '/report-titles'
    | '/reports'
    | '/reports/view/$groupId'
    | '/prs/finance'
    | '/prs/inbox'
    | '/prs/my-requests'
    | '/reports/submit'
    | '/prs/admin/form-templates'
    | '/prs/admin/team-configs'
    | '/prs/admin/teams'
    | '/prs/admin/workflows'
    | '/prs/requests/$requestId'
    | '/prs/requests/new'
    | '/report-titles/$reportTitleId/define-field'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(dashboard)/_dashboardLayout'
    | '/(dashboard)/_dashboardLayout/admin-review/$groupId'
    | '/(dashboard)/_dashboardLayout/admin-review/'
    | '/(dashboard)/_dashboardLayout/basic-info/'
    | '/(dashboard)/_dashboardLayout/change-password/'
    | '/(dashboard)/_dashboardLayout/company-basic-info/'
    | '/(dashboard)/_dashboardLayout/groups/'
    | '/(dashboard)/_dashboardLayout/input-demo/'
    | '/(dashboard)/_dashboardLayout/operations/'
    | '/(dashboard)/_dashboardLayout/report-titles/'
    | '/(dashboard)/_dashboardLayout/reports/'
    | '/(dashboard)/_dashboardLayout/reports/view/$groupId'
    | '/(dashboard)/_dashboardLayout/prs/finance/'
    | '/(dashboard)/_dashboardLayout/prs/inbox/'
    | '/(dashboard)/_dashboardLayout/prs/my-requests/'
    | '/(dashboard)/_dashboardLayout/reports/submit/'
    | '/(dashboard)/_dashboardLayout/prs/admin/form-templates/'
    | '/(dashboard)/_dashboardLayout/prs/admin/team-configs/'
    | '/(dashboard)/_dashboardLayout/prs/admin/teams/'
    | '/(dashboard)/_dashboardLayout/prs/admin/workflows/'
    | '/(dashboard)/_dashboardLayout/prs/requests/$requestId/'
    | '/(dashboard)/_dashboardLayout/prs/requests/new/'
    | '/(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  dashboardDashboardLayoutRoute: typeof dashboardDashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_dashboardLayout': {
      id: '/(dashboard)/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardDashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_dashboardLayout/reports/': {
      id: '/(dashboard)/_dashboardLayout/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof dashboardDashboardLayoutReportsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/report-titles/': {
      id: '/(dashboard)/_dashboardLayout/report-titles/'
      path: '/report-titles'
      fullPath: '/report-titles'
      preLoaderRoute: typeof dashboardDashboardLayoutReportTitlesIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/operations/': {
      id: '/(dashboard)/_dashboardLayout/operations/'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof dashboardDashboardLayoutOperationsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/input-demo/': {
      id: '/(dashboard)/_dashboardLayout/input-demo/'
      path: '/input-demo'
      fullPath: '/input-demo'
      preLoaderRoute: typeof dashboardDashboardLayoutInputDemoIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/groups/': {
      id: '/(dashboard)/_dashboardLayout/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof dashboardDashboardLayoutGroupsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/company-basic-info/': {
      id: '/(dashboard)/_dashboardLayout/company-basic-info/'
      path: '/company-basic-info'
      fullPath: '/company-basic-info'
      preLoaderRoute: typeof dashboardDashboardLayoutCompanyBasicInfoIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/change-password/': {
      id: '/(dashboard)/_dashboardLayout/change-password/'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof dashboardDashboardLayoutChangePasswordIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/basic-info/': {
      id: '/(dashboard)/_dashboardLayout/basic-info/'
      path: '/basic-info'
      fullPath: '/basic-info'
      preLoaderRoute: typeof dashboardDashboardLayoutBasicInfoIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/admin-review/': {
      id: '/(dashboard)/_dashboardLayout/admin-review/'
      path: '/admin-review'
      fullPath: '/admin-review'
      preLoaderRoute: typeof dashboardDashboardLayoutAdminReviewIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/admin-review/$groupId': {
      id: '/(dashboard)/_dashboardLayout/admin-review/$groupId'
      path: '/admin-review/$groupId'
      fullPath: '/admin-review/$groupId'
      preLoaderRoute: typeof dashboardDashboardLayoutAdminReviewGroupIdRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/reports/submit/': {
      id: '/(dashboard)/_dashboardLayout/reports/submit/'
      path: '/reports/submit'
      fullPath: '/reports/submit'
      preLoaderRoute: typeof dashboardDashboardLayoutReportsSubmitIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/prs/my-requests/': {
      id: '/(dashboard)/_dashboardLayout/prs/my-requests/'
      path: '/prs/my-requests'
      fullPath: '/prs/my-requests'
      preLoaderRoute: typeof dashboardDashboardLayoutPrsMyRequestsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/prs/inbox/': {
      id: '/(dashboard)/_dashboardLayout/prs/inbox/'
      path: '/prs/inbox'
      fullPath: '/prs/inbox'
      preLoaderRoute: typeof dashboardDashboardLayoutPrsInboxIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/prs/finance/': {
      id: '/(dashboard)/_dashboardLayout/prs/finance/'
      path: '/prs/finance'
      fullPath: '/prs/finance'
      preLoaderRoute: typeof dashboardDashboardLayoutPrsFinanceIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/reports/view/$groupId': {
      id: '/(dashboard)/_dashboardLayout/reports/view/$groupId'
      path: '/reports/view/$groupId'
      fullPath: '/reports/view/$groupId'
      preLoaderRoute: typeof dashboardDashboardLayoutReportsViewGroupIdRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/': {
      id: '/(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/'
      path: '/report-titles/$reportTitleId/define-field'
      fullPath: '/report-titles/$reportTitleId/define-field'
      preLoaderRoute: typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/prs/requests/new/': {
      id: '/(dashboard)/_dashboardLayout/prs/requests/new/'
      path: '/prs/requests/new'
      fullPath: '/prs/requests/new'
      preLoaderRoute: typeof dashboardDashboardLayoutPrsRequestsNewIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/prs/requests/$requestId/': {
      id: '/(dashboard)/_dashboardLayout/prs/requests/$requestId/'
      path: '/prs/requests/$requestId'
      fullPath: '/prs/requests/$requestId'
      preLoaderRoute: typeof dashboardDashboardLayoutPrsRequestsRequestIdIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/prs/admin/workflows/': {
      id: '/(dashboard)/_dashboardLayout/prs/admin/workflows/'
      path: '/prs/admin/workflows'
      fullPath: '/prs/admin/workflows'
      preLoaderRoute: typeof dashboardDashboardLayoutPrsAdminWorkflowsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/prs/admin/teams/': {
      id: '/(dashboard)/_dashboardLayout/prs/admin/teams/'
      path: '/prs/admin/teams'
      fullPath: '/prs/admin/teams'
      preLoaderRoute: typeof dashboardDashboardLayoutPrsAdminTeamsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/prs/admin/team-configs/': {
      id: '/(dashboard)/_dashboardLayout/prs/admin/team-configs/'
      path: '/prs/admin/team-configs'
      fullPath: '/prs/admin/team-configs'
      preLoaderRoute: typeof dashboardDashboardLayoutPrsAdminTeamConfigsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/prs/admin/form-templates/': {
      id: '/(dashboard)/_dashboardLayout/prs/admin/form-templates/'
      path: '/prs/admin/form-templates'
      fullPath: '/prs/admin/form-templates'
      preLoaderRoute: typeof dashboardDashboardLayoutPrsAdminFormTemplatesIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
  }
}

interface dashboardDashboardLayoutRouteChildren {
  dashboardDashboardLayoutAdminReviewGroupIdRoute: typeof dashboardDashboardLayoutAdminReviewGroupIdRoute
  dashboardDashboardLayoutAdminReviewIndexRoute: typeof dashboardDashboardLayoutAdminReviewIndexRoute
  dashboardDashboardLayoutBasicInfoIndexRoute: typeof dashboardDashboardLayoutBasicInfoIndexRoute
  dashboardDashboardLayoutChangePasswordIndexRoute: typeof dashboardDashboardLayoutChangePasswordIndexRoute
  dashboardDashboardLayoutCompanyBasicInfoIndexRoute: typeof dashboardDashboardLayoutCompanyBasicInfoIndexRoute
  dashboardDashboardLayoutGroupsIndexRoute: typeof dashboardDashboardLayoutGroupsIndexRoute
  dashboardDashboardLayoutInputDemoIndexRoute: typeof dashboardDashboardLayoutInputDemoIndexRoute
  dashboardDashboardLayoutOperationsIndexRoute: typeof dashboardDashboardLayoutOperationsIndexRoute
  dashboardDashboardLayoutReportTitlesIndexRoute: typeof dashboardDashboardLayoutReportTitlesIndexRoute
  dashboardDashboardLayoutReportsIndexRoute: typeof dashboardDashboardLayoutReportsIndexRoute
  dashboardDashboardLayoutReportsViewGroupIdRoute: typeof dashboardDashboardLayoutReportsViewGroupIdRoute
  dashboardDashboardLayoutPrsFinanceIndexRoute: typeof dashboardDashboardLayoutPrsFinanceIndexRoute
  dashboardDashboardLayoutPrsInboxIndexRoute: typeof dashboardDashboardLayoutPrsInboxIndexRoute
  dashboardDashboardLayoutPrsMyRequestsIndexRoute: typeof dashboardDashboardLayoutPrsMyRequestsIndexRoute
  dashboardDashboardLayoutReportsSubmitIndexRoute: typeof dashboardDashboardLayoutReportsSubmitIndexRoute
  dashboardDashboardLayoutPrsAdminFormTemplatesIndexRoute: typeof dashboardDashboardLayoutPrsAdminFormTemplatesIndexRoute
  dashboardDashboardLayoutPrsAdminTeamConfigsIndexRoute: typeof dashboardDashboardLayoutPrsAdminTeamConfigsIndexRoute
  dashboardDashboardLayoutPrsAdminTeamsIndexRoute: typeof dashboardDashboardLayoutPrsAdminTeamsIndexRoute
  dashboardDashboardLayoutPrsAdminWorkflowsIndexRoute: typeof dashboardDashboardLayoutPrsAdminWorkflowsIndexRoute
  dashboardDashboardLayoutPrsRequestsRequestIdIndexRoute: typeof dashboardDashboardLayoutPrsRequestsRequestIdIndexRoute
  dashboardDashboardLayoutPrsRequestsNewIndexRoute: typeof dashboardDashboardLayoutPrsRequestsNewIndexRoute
  dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute: typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute
}

const dashboardDashboardLayoutRouteChildren: dashboardDashboardLayoutRouteChildren =
  {
    dashboardDashboardLayoutAdminReviewGroupIdRoute:
      dashboardDashboardLayoutAdminReviewGroupIdRoute,
    dashboardDashboardLayoutAdminReviewIndexRoute:
      dashboardDashboardLayoutAdminReviewIndexRoute,
    dashboardDashboardLayoutBasicInfoIndexRoute:
      dashboardDashboardLayoutBasicInfoIndexRoute,
    dashboardDashboardLayoutChangePasswordIndexRoute:
      dashboardDashboardLayoutChangePasswordIndexRoute,
    dashboardDashboardLayoutCompanyBasicInfoIndexRoute:
      dashboardDashboardLayoutCompanyBasicInfoIndexRoute,
    dashboardDashboardLayoutGroupsIndexRoute:
      dashboardDashboardLayoutGroupsIndexRoute,
    dashboardDashboardLayoutInputDemoIndexRoute:
      dashboardDashboardLayoutInputDemoIndexRoute,
    dashboardDashboardLayoutOperationsIndexRoute:
      dashboardDashboardLayoutOperationsIndexRoute,
    dashboardDashboardLayoutReportTitlesIndexRoute:
      dashboardDashboardLayoutReportTitlesIndexRoute,
    dashboardDashboardLayoutReportsIndexRoute:
      dashboardDashboardLayoutReportsIndexRoute,
    dashboardDashboardLayoutReportsViewGroupIdRoute:
      dashboardDashboardLayoutReportsViewGroupIdRoute,
    dashboardDashboardLayoutPrsFinanceIndexRoute:
      dashboardDashboardLayoutPrsFinanceIndexRoute,
    dashboardDashboardLayoutPrsInboxIndexRoute:
      dashboardDashboardLayoutPrsInboxIndexRoute,
    dashboardDashboardLayoutPrsMyRequestsIndexRoute:
      dashboardDashboardLayoutPrsMyRequestsIndexRoute,
    dashboardDashboardLayoutReportsSubmitIndexRoute:
      dashboardDashboardLayoutReportsSubmitIndexRoute,
    dashboardDashboardLayoutPrsAdminFormTemplatesIndexRoute:
      dashboardDashboardLayoutPrsAdminFormTemplatesIndexRoute,
    dashboardDashboardLayoutPrsAdminTeamConfigsIndexRoute:
      dashboardDashboardLayoutPrsAdminTeamConfigsIndexRoute,
    dashboardDashboardLayoutPrsAdminTeamsIndexRoute:
      dashboardDashboardLayoutPrsAdminTeamsIndexRoute,
    dashboardDashboardLayoutPrsAdminWorkflowsIndexRoute:
      dashboardDashboardLayoutPrsAdminWorkflowsIndexRoute,
    dashboardDashboardLayoutPrsRequestsRequestIdIndexRoute:
      dashboardDashboardLayoutPrsRequestsRequestIdIndexRoute,
    dashboardDashboardLayoutPrsRequestsNewIndexRoute:
      dashboardDashboardLayoutPrsRequestsNewIndexRoute,
    dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute:
      dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute,
  }

const dashboardDashboardLayoutRouteWithChildren =
  dashboardDashboardLayoutRoute._addFileChildren(
    dashboardDashboardLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  dashboardDashboardLayoutRoute: dashboardDashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
