/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './__root'
import { Route as LoginRouteImport } from './login'
import { Route as IndexRouteImport } from './index'
import { Route as dashboardDashboardLayoutRouteImport } from './(dashboard)/_dashboardLayout'
import { Route as dashboardDashboardLayoutReportsIndexRouteImport } from './(dashboard)/_dashboardLayout/reports/index'
import { Route as dashboardDashboardLayoutReportTitlesIndexRouteImport } from './(dashboard)/_dashboardLayout/report-titles/index'
import { Route as dashboardDashboardLayoutOperationsIndexRouteImport } from './(dashboard)/_dashboardLayout/operations/index'
import { Route as dashboardDashboardLayoutInputDemoIndexRouteImport } from './(dashboard)/_dashboardLayout/input-demo/index'
import { Route as dashboardDashboardLayoutGroupsIndexRouteImport } from './(dashboard)/_dashboardLayout/groups/index'
import { Route as dashboardDashboardLayoutCompanyBasicInfoIndexRouteImport } from './(dashboard)/_dashboardLayout/company-basic-info/index'
import { Route as dashboardDashboardLayoutChangePasswordIndexRouteImport } from './(dashboard)/_dashboardLayout/change-password/index'
import { Route as dashboardDashboardLayoutBasicInfoIndexRouteImport } from './(dashboard)/_dashboardLayout/basic-info/index'
import { Route as dashboardDashboardLayoutAdminReviewIndexRouteImport } from './(dashboard)/_dashboardLayout/admin-review/index'
import { Route as dashboardDashboardLayoutAdminReviewGroupIdRouteImport } from './(dashboard)/_dashboardLayout/admin-review/$groupId'
import { Route as dashboardDashboardLayoutReportsSubmitIndexRouteImport } from './(dashboard)/_dashboardLayout/reports/submit/index'
import { Route as dashboardDashboardLayoutReportsViewGroupIdRouteImport } from './(dashboard)/_dashboardLayout/reports/view/$groupId'
import { Route as dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRouteImport } from './(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardLayoutRoute =
  dashboardDashboardLayoutRouteImport.update({
    id: '/(dashboard)/_dashboardLayout',
    getParentRoute: () => rootRouteImport,
  } as any)
const dashboardDashboardLayoutReportsIndexRoute =
  dashboardDashboardLayoutReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutReportTitlesIndexRoute =
  dashboardDashboardLayoutReportTitlesIndexRouteImport.update({
    id: '/report-titles/',
    path: '/report-titles/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutOperationsIndexRoute =
  dashboardDashboardLayoutOperationsIndexRouteImport.update({
    id: '/operations/',
    path: '/operations/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutInputDemoIndexRoute =
  dashboardDashboardLayoutInputDemoIndexRouteImport.update({
    id: '/input-demo/',
    path: '/input-demo/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutGroupsIndexRoute =
  dashboardDashboardLayoutGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutCompanyBasicInfoIndexRoute =
  dashboardDashboardLayoutCompanyBasicInfoIndexRouteImport.update({
    id: '/company-basic-info/',
    path: '/company-basic-info/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutChangePasswordIndexRoute =
  dashboardDashboardLayoutChangePasswordIndexRouteImport.update({
    id: '/change-password/',
    path: '/change-password/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutBasicInfoIndexRoute =
  dashboardDashboardLayoutBasicInfoIndexRouteImport.update({
    id: '/basic-info/',
    path: '/basic-info/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutAdminReviewIndexRoute =
  dashboardDashboardLayoutAdminReviewIndexRouteImport.update({
    id: '/admin-review/',
    path: '/admin-review/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutAdminReviewGroupIdRoute =
  dashboardDashboardLayoutAdminReviewGroupIdRouteImport.update({
    id: '/admin-review/$groupId',
    path: '/admin-review/$groupId',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutReportsSubmitIndexRoute =
  dashboardDashboardLayoutReportsSubmitIndexRouteImport.update({
    id: '/reports/submit/',
    path: '/reports/submit/',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutReportsViewGroupIdRoute =
  dashboardDashboardLayoutReportsViewGroupIdRouteImport.update({
    id: '/reports/view/$groupId',
    path: '/reports/view/$groupId',
    getParentRoute: () => dashboardDashboardLayoutRoute,
  } as any)
const dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute =
  dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRouteImport.update(
    {
      id: '/report-titles/$reportTitleId/define-field/',
      path: '/report-titles/$reportTitleId/define-field/',
      getParentRoute: () => dashboardDashboardLayoutRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-review/$groupId': typeof dashboardDashboardLayoutAdminReviewGroupIdRoute
  '/admin-review': typeof dashboardDashboardLayoutAdminReviewIndexRoute
  '/basic-info': typeof dashboardDashboardLayoutBasicInfoIndexRoute
  '/change-password': typeof dashboardDashboardLayoutChangePasswordIndexRoute
  '/company-basic-info': typeof dashboardDashboardLayoutCompanyBasicInfoIndexRoute
  '/groups': typeof dashboardDashboardLayoutGroupsIndexRoute
  '/input-demo': typeof dashboardDashboardLayoutInputDemoIndexRoute
  '/operations': typeof dashboardDashboardLayoutOperationsIndexRoute
  '/report-titles': typeof dashboardDashboardLayoutReportTitlesIndexRoute
  '/reports': typeof dashboardDashboardLayoutReportsIndexRoute
  '/reports/view/$groupId': typeof dashboardDashboardLayoutReportsViewGroupIdRoute
  '/reports/submit': typeof dashboardDashboardLayoutReportsSubmitIndexRoute
  '/report-titles/$reportTitleId/define-field': typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin-review/$groupId': typeof dashboardDashboardLayoutAdminReviewGroupIdRoute
  '/admin-review': typeof dashboardDashboardLayoutAdminReviewIndexRoute
  '/basic-info': typeof dashboardDashboardLayoutBasicInfoIndexRoute
  '/change-password': typeof dashboardDashboardLayoutChangePasswordIndexRoute
  '/company-basic-info': typeof dashboardDashboardLayoutCompanyBasicInfoIndexRoute
  '/groups': typeof dashboardDashboardLayoutGroupsIndexRoute
  '/input-demo': typeof dashboardDashboardLayoutInputDemoIndexRoute
  '/operations': typeof dashboardDashboardLayoutOperationsIndexRoute
  '/report-titles': typeof dashboardDashboardLayoutReportTitlesIndexRoute
  '/reports': typeof dashboardDashboardLayoutReportsIndexRoute
  '/reports/view/$groupId': typeof dashboardDashboardLayoutReportsViewGroupIdRoute
  '/reports/submit': typeof dashboardDashboardLayoutReportsSubmitIndexRoute
  '/report-titles/$reportTitleId/define-field': typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/(dashboard)/_dashboardLayout': typeof dashboardDashboardLayoutRouteWithChildren
  '/(dashboard)/_dashboardLayout/admin-review/$groupId': typeof dashboardDashboardLayoutAdminReviewGroupIdRoute
  '/(dashboard)/_dashboardLayout/admin-review/': typeof dashboardDashboardLayoutAdminReviewIndexRoute
  '/(dashboard)/_dashboardLayout/basic-info/': typeof dashboardDashboardLayoutBasicInfoIndexRoute
  '/(dashboard)/_dashboardLayout/change-password/': typeof dashboardDashboardLayoutChangePasswordIndexRoute
  '/(dashboard)/_dashboardLayout/company-basic-info/': typeof dashboardDashboardLayoutCompanyBasicInfoIndexRoute
  '/(dashboard)/_dashboardLayout/groups/': typeof dashboardDashboardLayoutGroupsIndexRoute
  '/(dashboard)/_dashboardLayout/input-demo/': typeof dashboardDashboardLayoutInputDemoIndexRoute
  '/(dashboard)/_dashboardLayout/operations/': typeof dashboardDashboardLayoutOperationsIndexRoute
  '/(dashboard)/_dashboardLayout/report-titles/': typeof dashboardDashboardLayoutReportTitlesIndexRoute
  '/(dashboard)/_dashboardLayout/reports/': typeof dashboardDashboardLayoutReportsIndexRoute
  '/(dashboard)/_dashboardLayout/reports/view/$groupId': typeof dashboardDashboardLayoutReportsViewGroupIdRoute
  '/(dashboard)/_dashboardLayout/reports/submit/': typeof dashboardDashboardLayoutReportsSubmitIndexRoute
  '/(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/': typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-review/$groupId'
    | '/admin-review'
    | '/basic-info'
    | '/change-password'
    | '/company-basic-info'
    | '/groups'
    | '/input-demo'
    | '/operations'
    | '/report-titles'
    | '/reports'
    | '/reports/view/$groupId'
    | '/reports/submit'
    | '/report-titles/$reportTitleId/define-field'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin-review/$groupId'
    | '/admin-review'
    | '/basic-info'
    | '/change-password'
    | '/company-basic-info'
    | '/groups'
    | '/input-demo'
    | '/operations'
    | '/report-titles'
    | '/reports'
    | '/reports/view/$groupId'
    | '/reports/submit'
    | '/report-titles/$reportTitleId/define-field'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/(dashboard)/_dashboardLayout'
    | '/(dashboard)/_dashboardLayout/admin-review/$groupId'
    | '/(dashboard)/_dashboardLayout/admin-review/'
    | '/(dashboard)/_dashboardLayout/basic-info/'
    | '/(dashboard)/_dashboardLayout/change-password/'
    | '/(dashboard)/_dashboardLayout/company-basic-info/'
    | '/(dashboard)/_dashboardLayout/groups/'
    | '/(dashboard)/_dashboardLayout/input-demo/'
    | '/(dashboard)/_dashboardLayout/operations/'
    | '/(dashboard)/_dashboardLayout/report-titles/'
    | '/(dashboard)/_dashboardLayout/reports/'
    | '/(dashboard)/_dashboardLayout/reports/view/$groupId'
    | '/(dashboard)/_dashboardLayout/reports/submit/'
    | '/(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  dashboardDashboardLayoutRoute: typeof dashboardDashboardLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_dashboardLayout': {
      id: '/(dashboard)/_dashboardLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardDashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/_dashboardLayout/reports/': {
      id: '/(dashboard)/_dashboardLayout/reports/'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof dashboardDashboardLayoutReportsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/report-titles/': {
      id: '/(dashboard)/_dashboardLayout/report-titles/'
      path: '/report-titles'
      fullPath: '/report-titles'
      preLoaderRoute: typeof dashboardDashboardLayoutReportTitlesIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/operations/': {
      id: '/(dashboard)/_dashboardLayout/operations/'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof dashboardDashboardLayoutOperationsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/input-demo/': {
      id: '/(dashboard)/_dashboardLayout/input-demo/'
      path: '/input-demo'
      fullPath: '/input-demo'
      preLoaderRoute: typeof dashboardDashboardLayoutInputDemoIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/groups/': {
      id: '/(dashboard)/_dashboardLayout/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof dashboardDashboardLayoutGroupsIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/company-basic-info/': {
      id: '/(dashboard)/_dashboardLayout/company-basic-info/'
      path: '/company-basic-info'
      fullPath: '/company-basic-info'
      preLoaderRoute: typeof dashboardDashboardLayoutCompanyBasicInfoIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/change-password/': {
      id: '/(dashboard)/_dashboardLayout/change-password/'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof dashboardDashboardLayoutChangePasswordIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/basic-info/': {
      id: '/(dashboard)/_dashboardLayout/basic-info/'
      path: '/basic-info'
      fullPath: '/basic-info'
      preLoaderRoute: typeof dashboardDashboardLayoutBasicInfoIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/admin-review/': {
      id: '/(dashboard)/_dashboardLayout/admin-review/'
      path: '/admin-review'
      fullPath: '/admin-review'
      preLoaderRoute: typeof dashboardDashboardLayoutAdminReviewIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/admin-review/$groupId': {
      id: '/(dashboard)/_dashboardLayout/admin-review/$groupId'
      path: '/admin-review/$groupId'
      fullPath: '/admin-review/$groupId'
      preLoaderRoute: typeof dashboardDashboardLayoutAdminReviewGroupIdRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/reports/submit/': {
      id: '/(dashboard)/_dashboardLayout/reports/submit/'
      path: '/reports/submit'
      fullPath: '/reports/submit'
      preLoaderRoute: typeof dashboardDashboardLayoutReportsSubmitIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/reports/view/$groupId': {
      id: '/(dashboard)/_dashboardLayout/reports/view/$groupId'
      path: '/reports/view/$groupId'
      fullPath: '/reports/view/$groupId'
      preLoaderRoute: typeof dashboardDashboardLayoutReportsViewGroupIdRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
    '/(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/': {
      id: '/(dashboard)/_dashboardLayout/report-titles/$reportTitleId/define-field/'
      path: '/report-titles/$reportTitleId/define-field'
      fullPath: '/report-titles/$reportTitleId/define-field'
      preLoaderRoute: typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRouteImport
      parentRoute: typeof dashboardDashboardLayoutRoute
    }
  }
}

interface dashboardDashboardLayoutRouteChildren {
  dashboardDashboardLayoutAdminReviewGroupIdRoute: typeof dashboardDashboardLayoutAdminReviewGroupIdRoute
  dashboardDashboardLayoutAdminReviewIndexRoute: typeof dashboardDashboardLayoutAdminReviewIndexRoute
  dashboardDashboardLayoutBasicInfoIndexRoute: typeof dashboardDashboardLayoutBasicInfoIndexRoute
  dashboardDashboardLayoutChangePasswordIndexRoute: typeof dashboardDashboardLayoutChangePasswordIndexRoute
  dashboardDashboardLayoutCompanyBasicInfoIndexRoute: typeof dashboardDashboardLayoutCompanyBasicInfoIndexRoute
  dashboardDashboardLayoutGroupsIndexRoute: typeof dashboardDashboardLayoutGroupsIndexRoute
  dashboardDashboardLayoutInputDemoIndexRoute: typeof dashboardDashboardLayoutInputDemoIndexRoute
  dashboardDashboardLayoutOperationsIndexRoute: typeof dashboardDashboardLayoutOperationsIndexRoute
  dashboardDashboardLayoutReportTitlesIndexRoute: typeof dashboardDashboardLayoutReportTitlesIndexRoute
  dashboardDashboardLayoutReportsIndexRoute: typeof dashboardDashboardLayoutReportsIndexRoute
  dashboardDashboardLayoutReportsViewGroupIdRoute: typeof dashboardDashboardLayoutReportsViewGroupIdRoute
  dashboardDashboardLayoutReportsSubmitIndexRoute: typeof dashboardDashboardLayoutReportsSubmitIndexRoute
  dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute: typeof dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute
}

const dashboardDashboardLayoutRouteChildren: dashboardDashboardLayoutRouteChildren =
  {
    dashboardDashboardLayoutAdminReviewGroupIdRoute:
      dashboardDashboardLayoutAdminReviewGroupIdRoute,
    dashboardDashboardLayoutAdminReviewIndexRoute:
      dashboardDashboardLayoutAdminReviewIndexRoute,
    dashboardDashboardLayoutBasicInfoIndexRoute:
      dashboardDashboardLayoutBasicInfoIndexRoute,
    dashboardDashboardLayoutChangePasswordIndexRoute:
      dashboardDashboardLayoutChangePasswordIndexRoute,
    dashboardDashboardLayoutCompanyBasicInfoIndexRoute:
      dashboardDashboardLayoutCompanyBasicInfoIndexRoute,
    dashboardDashboardLayoutGroupsIndexRoute:
      dashboardDashboardLayoutGroupsIndexRoute,
    dashboardDashboardLayoutInputDemoIndexRoute:
      dashboardDashboardLayoutInputDemoIndexRoute,
    dashboardDashboardLayoutOperationsIndexRoute:
      dashboardDashboardLayoutOperationsIndexRoute,
    dashboardDashboardLayoutReportTitlesIndexRoute:
      dashboardDashboardLayoutReportTitlesIndexRoute,
    dashboardDashboardLayoutReportsIndexRoute:
      dashboardDashboardLayoutReportsIndexRoute,
    dashboardDashboardLayoutReportsViewGroupIdRoute:
      dashboardDashboardLayoutReportsViewGroupIdRoute,
    dashboardDashboardLayoutReportsSubmitIndexRoute:
      dashboardDashboardLayoutReportsSubmitIndexRoute,
    dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute:
      dashboardDashboardLayoutReportTitlesReportTitleIdDefineFieldIndexRoute,
  }

const dashboardDashboardLayoutRouteWithChildren =
  dashboardDashboardLayoutRoute._addFileChildren(
    dashboardDashboardLayoutRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  dashboardDashboardLayoutRoute: dashboardDashboardLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
