# Generated by Django 5.2.8 on 2025-01-XX XX:XX

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportBox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('intercompany', models.BooleanField(default=False)),
                ('classifications', models.ManyToManyField(blank=True, limit_choices_to={'type__code': 'COMPANY_CLASSIFICATION'}, related_name='reports', to='classifications.lookup')),
                ('groups', models.ManyToManyField(blank=True, related_name='reports', to='reports.reportgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReportField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('field_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('data_type', models.CharField(choices=[('NUMBER', 'Number'), ('TEXT', 'Text'), ('YES_NO', 'Yes/No'), ('DATE', 'Date'), ('FILE', 'File'), ('ENTITY_REF', 'Entity Reference')], max_length=16)),
                ('entity_ref_type', models.CharField(blank=True, choices=[('ORG_NODE', 'Organization Node'), ('FINANCIAL_PERIOD', 'Financial Period')], max_length=32, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='reports.reportbox')),
            ],
            options={
                'unique_together': {('report', 'field_id')},
            },
        ),
        migrations.AddIndex(
            model_name='reportfield',
            index=models.Index(fields=['report', 'field_id'], name='reports_rep_report__idx'),
        ),
        migrations.AddConstraint(
            model_name='reportfield',
            constraint=models.CheckConstraint(check=Q(data_type='ENTITY_REF') | Q(entity_ref_type__isnull=True), name='entity_ref_type_null_when_not_ref'),
        ),
        migrations.AddConstraint(
            model_name='reportfield',
            constraint=models.CheckConstraint(check=~Q(data_type='ENTITY_REF') | Q(entity_ref_type__isnull=False), name='entity_ref_type_set_when_ref'),
        ),
    ]

