# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportfield',
            new_name='reports_rep_report__8c36ab_idx',
            old_name='reports_rep_report__idx',
        ),
    ]
