# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='team',
            new_name='teams_team_is_acti_c08f54_idx',
            old_name='teams_team_is_acti_idx',
        ),
    ]
