# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_request_f5fc49_idx',
            old_name='attachment_request_idx',
        ),
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_request_ec784c_idx',
            old_name='attachment_request_2_idx',
        ),
        migrations.RenameIndex(
            model_name='attachmentcategory',
            new_name='attachments_team_id_b5a692_idx',
            old_name='attachment_team_id_idx',
        ),
    ]
