# Generated by Django 5.2.8 on 2025-11-30 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attachments', '0003_add_approval_history_to_attachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attachment',
            new_name='attachments_approva_ccaaf2_idx',
            old_name='attachments_approval_idx',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file_path',
            field=models.FileField(upload_to='request_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'docx', 'xlsx', 'xls'])]),
        ),
    ]
