# Generated by Django 5.2.8 on 2025-11-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prs_forms', '0002_rename_prs_forms_formfie_templat_idx_prs_forms_f_templat_7eb318_idx_and_more'),
        ('purchase_requests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='requestfieldvalue',
            name='single_value_column',
        ),
        migrations.RenameIndex(
            model_name='purchaserequest',
            new_name='purchase_re_status__a2d28a_idx',
            old_name='purchase_r_status__idx',
        ),
        migrations.RenameIndex(
            model_name='purchaserequest',
            new_name='purchase_re_request_6d56cf_idx',
            old_name='purchase_r_request_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaserequest',
            new_name='purchase_re_team_id_1bd6b8_idx',
            old_name='purchase_r_team_id_idx',
        ),
        migrations.RenameIndex(
            model_name='purchaserequest',
            new_name='purchase_re_status__8f446c_idx',
            old_name='purchase_r_status__2_idx',
        ),
        migrations.RenameIndex(
            model_name='requestfieldvalue',
            new_name='purchase_re_request_ed1b50_idx',
            old_name='purchase_r_request_2_idx',
        ),
        migrations.AddConstraint(
            model_name='requestfieldvalue',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('value_number__isnull', True), ('value_text__isnull', True), _connector='OR'), models.Q(('value_number__isnull', True), ('value_bool__isnull', True), _connector='OR'), models.Q(('value_number__isnull', True), ('value_date__isnull', True), _connector='OR'), models.Q(('value_number__isnull', True), ('value_dropdown__isnull', True), _connector='OR'), models.Q(('value_text__isnull', True), ('value_bool__isnull', True), _connector='OR'), models.Q(('value_text__isnull', True), ('value_date__isnull', True), _connector='OR'), models.Q(('value_text__isnull', True), ('value_dropdown__isnull', True), _connector='OR'), models.Q(('value_bool__isnull', True), ('value_date__isnull', True), _connector='OR'), models.Q(('value_bool__isnull', True), ('value_dropdown__isnull', True), _connector='OR'), models.Q(('value_date__isnull', True), ('value_dropdown__isnull', True), _connector='OR')), name='prs_requestfieldvalue_single_value_column'),
        ),
    ]
